version: "3"
services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-net
  generator-api:
    image: rag-generator-api:latest
    container_name: generator-api
    build:
      context: .
      dockerfile: ./generator-api/Dockerfile
    ports:
      - 8000:8000
    networks:
      - opensearch-net
  retriever-api:
    image: rag-retriever-api:latest
    container_name: retriever-api
    build:
      context: .
      dockerfile: ./retriever-api/Dockerfile
    environment:
      - OPENSEARCH_HOST=opensearch
      - OPENSEARCH_PORT=9200
      - OPENSEARCH_INDEX=rag-index
    ports:
      - 4000:4000
    networks:
      - opensearch-net
  rag-api:
    image: rag-core-api:latest
    container_name: rag-api
    build:
      context: .
      dockerfile: ./rag-api/Dockerfile
    environment:
      - RETRIEVER_URL=http://retriever-api:4000/retrieve
      - GENERATOR_URL=http://generator-api:8000/generate
    ports:
      - 9000:9000
    networks:
      - opensearch-net

networks:
  opensearch-net:
